---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: centos-7
    image: centos:7
  - name: ubuntu-16.04
    image: ubuntu:16.04
  - name: ubuntu-18.04
    image: ubuntu:18.04
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    host_vars:
      centos-7:
        graalvm_ce_version: 19.3.1
      ubuntu-16.04:
        graalvm_ce_version: 19.3.1
      ubuntu-18.04:
        graalvm_ce_version: 19.3.1

verifier:
  name: testinfra
  lint:
    name: flake8
